name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag otzro/gphotos-sync:$(date +%s) --tag otzro/gphotos-sync:latest
    - name: Push the Docker image with date
      run: docker push otzro/gphotos-sync:$(date +%s)
    - name: Push the Docker image latest
      run: docker push otzro/gphotos-sync:latest
